### ISSUE TITLE
Could this package add License file

### ISSUE THREAD

**Issue by yechun1** [intel/object_msgs#2]
What is the License of this object_msgs package

**Comment by xhuan28** [comment]
@yechun1 , fix in this [commit](https://github.com/intel/object_msgs/commit/b68c5de09c7d7c4aa455a8123bd5ce8731a4e2c7).

**Comment by Manoj-Bhat97** [comment]
Hello @xhuan28 , I want to use this package for object detection using Intel r200 IR sensors and simulate its accuracy in Gazebo. Can I use this for the same?

**Comment by chaoli2** [comment]
@DarshanLakkundi 
This project is an open source customized message for object classification and detection. You can use it in your object detection project.
I also recommend you another [message project ](https://github.com/Kukanani/vision_msgs)for your reference.
